### ISSUE TITLE
Extends support

### ISSUE THREAD

**Issue by kenanchristian** [Roobyx/Autocompiler-Pug-Jade#5]
![image](https://cloud.githubusercontent.com/assets/11202498/24450776/56cb6b1a-14a6-11e7-9af3-ed7534cedf2e.png)

This is the current code that i have
I'm trying to extend `index.pug` to `layout.pug` but the plugin always tries to search for `.jade` file instead of `.pug` file. Is this an expected behavior, so i must use `.jade` if i want to use extends?
 
note: yeah i know that i got indentation from the block syntax wrong, just fixed that but still got the same error :)

**Comment by Roobyx** [comment]
The issue is duplicate of https://github.com/Roobyx/Autocompiler-Pug-Jade/issues/3

I will try to look for a fix the upcoming days.
I am not actively supporting the extensions, since I moved to VS Code for quite a long time now. And I will probably port the exntesion there instead of keeping it only for Atom.
