### ISSUE TITLE
Only jade in extends or include

### ISSUE THREAD

**Issue by pablocastilloegoavil** [Roobyx/Autocompiler-Pug-Jade#6]
Can not use extension pug in include or extends only jade extensions can be used

**Comment by rdhar** [comment]
It's been about a month since this issue was opened; has it been addressed yet? I tried the following code for [template inheritance](https://pugjs.org/language/inheritance.html):
```
// output:$1.html
extends structure/_layout.jade
```
This failed to compile with the following error message:
> D:\project\index.pug:1 ENOENT: no such file or directory, open 'D:\project\structure_layout.pug.jade'

For some reason, it failed to parse the slash after "structure" and appended `.jade` to the `_layout.pug`. As soon as the file is renamed to `_layout.jade`, this issue is resolved. However, as per [Pug 2](https://pugjs.org/api/migration-v2.html), `.jade` file extension is supported but deprecated. Note, the `index.pug` file _does_ compile successfully so there must be some support for it.

As such, is there a way to refer to `.pug` files for includes & extends as it's one of the most significant advantages over HTML? Thanks.

**Comment by Roobyx** [comment]
Please refer to issue #3 : https://github.com/Roobyx/Autocompiler-Pug-Jade/issues/3

It is not a problem with the package itself. I hope I can look into it again soon. I am sorry for resolving it soon.
